// Code generated by templ@v0.2.316 DO NOT EDIT.

package tictactoe

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Box(id string, symbol *rune) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<div")
		if err != nil {
			return err
		}
		if symbol == nil {
			_, err = templBuffer.WriteString(" ws-send")
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString(" name=\"cell\" id=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(id))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" class=\"bg-muted flex items-center justify-center text-8xl font-bold cursor-pointer w-full aspect-square text-primary\">")
		if err != nil {
			return err
		}
		if symbol != nil {
			var var_2 string = string(*symbol)
			_, err = templBuffer.WriteString(templ.EscapeString(var_2))
			if err != nil {
				return err
			}
		} else {
			var var_3 string = " "
			_, err = templBuffer.WriteString(templ.EscapeString(var_3))
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("</div>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = io.Copy(w, templBuffer)
		}
		return err
	})
}

func Board() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_4 := templ.GetChildren(ctx)
		if var_4 == nil {
			var_4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<div id=\"board\" class=\"grid grid-cols-3 gap-2 aspect-square w-3/5\">")
		if err != nil {
			return err
		}
		err = Box("cell-1", nil).Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		err = Box("cell-2", nil).Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		err = Box("cell-3", nil).Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		err = Box("cell-4", nil).Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		err = Box("cell-5", nil).Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		err = Box("cell-6", nil).Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		err = Box("cell-7", nil).Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		err = Box("cell-8", nil).Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		err = Box("cell-9", nil).Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = io.Copy(w, templBuffer)
		}
		return err
	})
}

func Game() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_5 := templ.GetChildren(ctx)
		if var_5 == nil {
			var_5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<div id=\"ws-connection\" hx-swap-oob=\"innerHTML\"><h1 class=\"text-2xl font-semibold mb-4\">")
		if err != nil {
			return err
		}
		var_6 := `Tic-Tac-Toe`
		_, err = templBuffer.WriteString(var_6)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><div id=\"board-container\" class=\"flex items-center justify-center\">")
		if err != nil {
			return err
		}
		err = Board().Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div><button class=\"mt-4 bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-md\">")
		if err != nil {
			return err
		}
		var_7 := `Reset`
		_, err = templBuffer.WriteString(var_7)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</button></div>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = io.Copy(w, templBuffer)
		}
		return err
	})
}
